<?php

namespace RuffeCard\UserGestionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{
	
	
	public function FindClient($term){
		
		$qb = $this->createQueryBuilder('c');
		$qb->select('c.nom','c.prenom','c.id')
		
		->where('c.nom LIKE :term')
		->setParameter('term', $term .'%')
		->setMaxResults(10);
		$arrayAss = $qb->getQuery()
		->getArrayResult();
		$array = array();
		foreach ($arrayAss as $data) {
			
			$array[$data['id']] = $data['nom']." ".$data['prenom'];
		}
		return $array;
	}
	
	public function findClientNoPaiment(){
		
		$from = "RuffeCardUserGestionBundle:Client";
		$alias = "p";

		$qb = $this->_em->createQueryBuilder ()
		->select ( 'p' )
		->from ( $from, $alias )
		->where ( 'p.paiement  is NULL' );
		
		
		return $qb->getQuery ()->getResult ();
		
		
	}
	
	public function findClientPaiment(){
	
		$from = "RuffeCardUserGestionBundle:Client";
		$alias = "p";
	
		$qb = $this->_em->createQueryBuilder ()
		->select ( 'p' )
		->from ( $from, $alias )
		->where ( 'p.paiement  is not NULL' );
	
	
		return $qb->getQuery ()->getResult ();
	
	
	}
	
	
}
