<?php

namespace RuffeCard\UserGestionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntrepriseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntrepriseRepository extends EntityRepository
{
	
	public function FindEntreprise($term){

		$qb = $this->createQueryBuilder('c');
		$qb->select('c.societe,c.id')
		
		->where('c.societe LIKE :term')
		->setParameter('term', $term .'%')
		->setMaxResults(10);
		$arrayAss = $qb->getQuery()
		->getArrayResult();
		$array = array();
		foreach ($arrayAss as $data) {
				
			$array[$data['id']] = $data['societe'];
		}
		return $array;
	}
	public function findClientNoPaiment(){
	
		$from = "RuffeCardUserGestionBundle:Entreprise";
		$alias = "p";
	
		$qb = $this->_em->createQueryBuilder ()
		->select ( 'p' )
		->from ( $from, $alias )
		->where ( 'p.paiement  is NULL' );
	
	
		return $qb->getQuery ()->getResult ();
	
	
	}
	public function findClientPaiment(){
	
		$from = "RuffeCardUserGestionBundle:Entreprise";
		$alias = "p";
	
		$qb = $this->_em->createQueryBuilder ()
		->select ( 'p' )
		->from ( $from, $alias )
		->where ( 'p.paiement  is not NULL' );
	
	
		return $qb->getQuery ()->getResult ();
	
	
	}
	
}
